
medians_add_plac<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_200placebo_63d_ltf0.1.csv")
medians_add_plac$diff_PE<-medians_add_plac$PE30_high-medians_add_plac$PE30_low
medians_add_plac$diff_dur<-medians_add_plac$mean_dur_prot_high-medians_add_plac$mean_dur_prot_low
summary(medians_add_plac$diff_PE)
summary(medians_add_plac$diff_dur)
  
medians_add_AS<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_200AS_63d_ltf0.1.csv")
medians_add_AS$diff_PE<-medians_add_AS$PE30_high-medians_add_AS$PE30_low
medians_add_AS$diff_dur<-medians_add_AS$mean_dur_prot_high-medians_add_AS$mean_dur_prot_low
summary(medians_add_AS$diff_PE)
summary(medians_add_AS$diff_dur)

medians_baseline<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_63d_ltf0.1.csv")
medians_baseline$diff_PE<-medians_baseline$PE30_high-medians_baseline$PE30_low
medians_baseline$diff_dur<-medians_baseline$mean_dur_prot_high-medians_baseline$mean_dur_prot_low
summary(medians_baseline$diff_PE)
summary(medians_baseline$diff_dur)

medians_red_followup28<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_28d_ltf0.1.csv")
medians_red_followup28$diff_PE<-medians_red_followup28$PE30_high-medians_red_followup28$PE30_low
medians_red_followup28$diff_dur<-medians_red_followup28$mean_dur_prot_high-medians_red_followup28$mean_dur_prot_low
summary(medians_red_followup28$diff_PE)
summary(medians_red_followup28$diff_dur)


medians_red_followup42<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_42d_ltf0.1.csv")
medians_red_followup42$diff_PE<-medians_red_followup42$PE30_high-medians_red_followup42$PE30_low
medians_red_followup42$diff_dur<-medians_red_followup42$mean_dur_prot_high-medians_red_followup42$mean_dur_prot_low
summary(medians_red_followup42$diff_PE)
summary(medians_red_followup42$diff_dur)




medians_add_AS_red_followup28<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_200AS_28d_ltf0.1.csv")
medians_add_AS_red_followup28$diff_PE<-medians_add_AS_red_followup28$PE30_high-medians_add_AS_red_followup28$PE30_low
medians_add_AS_red_followup28$diff_dur<-medians_add_AS_red_followup28$mean_dur_prot_high-medians_add_AS_red_followup28$mean_dur_prot_low
summary(medians_add_AS_red_followup28$diff_PE)
summary(medians_add_AS_red_followup28$diff_dur)


medians_red_ltf0.2<-read.csv("saved_dfs/1strain_model/medians_20days_10ippy_prev0.4_seas_none_N600_63d_ltf0.2.csv")
medians_red_ltf0.2$diff_PE<-medians_red_ltf0.2$PE30_high-medians_red_ltf0.2$PE30_low
medians_red_ltf0.2$diff_dur<-medians_red_ltf0.2$mean_dur_prot_high-medians_red_ltf0.2$mean_dur_prot_low
summary(medians_red_ltf0.2$diff_PE)
summary(medians_red_ltf0.2$diff_dur)
